### ISSUE TITLE
Add cursor pointer to the silder on homepage 

### ISSUE THREAD

**Issue by adam-deriv** [mamali-fs/api-deriv-com-solidjs#29]
![image](https://user-images.githubusercontent.com/91898870/142873527-677b5fef-fad5-40cd-8acf-a60457952232.png)
also write test for this component to display cursor pointer and test its behaviour

e.g. add smaller machine sliderMachine, include possible states and include in those the cursor pointer check

**Comment by adam-deriv** [comment]
cc @hubert-deriv

**Comment by hubert-deriv** [comment]
Slider testing machine will be implemented by Ako.
