### ISSUE TITLE
Add routing between pages

### ISSUE THREAD

**Issue by adam-deriv** [mamali-fs/api-deriv-com-solidjs#4]

**Comment by adam-deriv** [comment]
connect to https://github.com/mamali-fs/api-deriv-com-solidjs/issues/7

**Comment by ali-hosseini-fs** [comment]
already done

**Comment by adam-deriv** [comment]
https://solidjs-deriv-api.netlify.app/docs (the content of sidebar cannot be displayed. (cc your problem with Quickstart @alamin-deriv)
I think this is related issue to the fact that <App/> component uses <Router/> and then <Docs/>  tries to use <Router /> again, when this is in conflict (Docs is already routed page). It should use children in routes object and <Outlet /> component  (FYI @Bahar-FS ) https://github.com/solidjs/solid-app-router#nested-routing
